// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: api/ocp-timeline-api/ocp_timeline_api.proto

package ocp_timeline_api

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MultiCreateTimelinesV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timelines []*Timeline `protobuf:"bytes,1,rep,name=timelines,proto3" json:"timelines,omitempty"`
}

func (x *MultiCreateTimelinesV1Request) Reset() {
	*x = MultiCreateTimelinesV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCreateTimelinesV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateTimelinesV1Request) ProtoMessage() {}

func (x *MultiCreateTimelinesV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateTimelinesV1Request.ProtoReflect.Descriptor instead.
func (*MultiCreateTimelinesV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{0}
}

func (x *MultiCreateTimelinesV1Request) GetTimelines() []*Timeline {
	if x != nil {
		return x.Timelines
	}
	return nil
}

type MultiCreateTimelinesV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Added bool `protobuf:"varint,1,opt,name=added,proto3" json:"added,omitempty"`
}

func (x *MultiCreateTimelinesV1Response) Reset() {
	*x = MultiCreateTimelinesV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiCreateTimelinesV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiCreateTimelinesV1Response) ProtoMessage() {}

func (x *MultiCreateTimelinesV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiCreateTimelinesV1Response.ProtoReflect.Descriptor instead.
func (*MultiCreateTimelinesV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{1}
}

func (x *MultiCreateTimelinesV1Response) GetAdded() bool {
	if x != nil {
		return x.Added
	}
	return false
}

type UpdateTimelineV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeline *Timeline `protobuf:"bytes,1,opt,name=timeline,proto3" json:"timeline,omitempty"`
}

func (x *UpdateTimelineV1Request) Reset() {
	*x = UpdateTimelineV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTimelineV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimelineV1Request) ProtoMessage() {}

func (x *UpdateTimelineV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimelineV1Request.ProtoReflect.Descriptor instead.
func (*UpdateTimelineV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateTimelineV1Request) GetTimeline() *Timeline {
	if x != nil {
		return x.Timeline
	}
	return nil
}

type UpdateTimelineV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Updated bool `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *UpdateTimelineV1Response) Reset() {
	*x = UpdateTimelineV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTimelineV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTimelineV1Response) ProtoMessage() {}

func (x *UpdateTimelineV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTimelineV1Response.ProtoReflect.Descriptor instead.
func (*UpdateTimelineV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTimelineV1Response) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

type CreateTimelineV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type   uint64 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	From   string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To     string `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *CreateTimelineV1Request) Reset() {
	*x = CreateTimelineV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimelineV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimelineV1Request) ProtoMessage() {}

func (x *CreateTimelineV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimelineV1Request.ProtoReflect.Descriptor instead.
func (*CreateTimelineV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTimelineV1Request) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTimelineV1Request) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateTimelineV1Request) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CreateTimelineV1Request) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type CreateTimelineV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateTimelineV1Response) Reset() {
	*x = CreateTimelineV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTimelineV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTimelineV1Response) ProtoMessage() {}

func (x *CreateTimelineV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTimelineV1Response.ProtoReflect.Descriptor instead.
func (*CreateTimelineV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{5}
}

func (x *CreateTimelineV1Response) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTimelineV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTimelineV1Request) Reset() {
	*x = GetTimelineV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimelineV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelineV1Request) ProtoMessage() {}

func (x *GetTimelineV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelineV1Request.ProtoReflect.Descriptor instead.
func (*GetTimelineV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{6}
}

func (x *GetTimelineV1Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTimelineV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timeline *Timeline `protobuf:"bytes,1,opt,name=timeline,proto3" json:"timeline,omitempty"`
}

func (x *GetTimelineV1Response) Reset() {
	*x = GetTimelineV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTimelineV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimelineV1Response) ProtoMessage() {}

func (x *GetTimelineV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimelineV1Response.ProtoReflect.Descriptor instead.
func (*GetTimelineV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetTimelineV1Response) GetTimeline() *Timeline {
	if x != nil {
		return x.Timeline
	}
	return nil
}

type ListTimelineV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit  uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListTimelineV1Request) Reset() {
	*x = ListTimelineV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTimelineV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimelineV1Request) ProtoMessage() {}

func (x *ListTimelineV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimelineV1Request.ProtoReflect.Descriptor instead.
func (*ListTimelineV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListTimelineV1Request) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTimelineV1Request) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTimelineV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total     uint64      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Timelines []*Timeline `protobuf:"bytes,2,rep,name=timelines,proto3" json:"timelines,omitempty"`
}

func (x *ListTimelineV1Response) Reset() {
	*x = ListTimelineV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTimelineV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTimelineV1Response) ProtoMessage() {}

func (x *ListTimelineV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTimelineV1Response.ProtoReflect.Descriptor instead.
func (*ListTimelineV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListTimelineV1Response) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTimelineV1Response) GetTimelines() []*Timeline {
	if x != nil {
		return x.Timelines
	}
	return nil
}

type RemoveTimelineV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RemoveTimelineV1Request) Reset() {
	*x = RemoveTimelineV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTimelineV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTimelineV1Request) ProtoMessage() {}

func (x *RemoveTimelineV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTimelineV1Request.ProtoReflect.Descriptor instead.
func (*RemoveTimelineV1Request) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveTimelineV1Request) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RemoveTimelineV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RemoveTimelineV1Response) Reset() {
	*x = RemoveTimelineV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTimelineV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTimelineV1Response) ProtoMessage() {}

func (x *RemoveTimelineV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTimelineV1Response.ProtoReflect.Descriptor instead.
func (*RemoveTimelineV1Response) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{11}
}

type Timeline struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId uint64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type   uint64 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	From   string `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To     string `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
}

func (x *Timeline) Reset() {
	*x = Timeline{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timeline) ProtoMessage() {}

func (x *Timeline) ProtoReflect() protoreflect.Message {
	mi := &file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timeline.ProtoReflect.Descriptor instead.
func (*Timeline) Descriptor() ([]byte, []int) {
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP(), []int{12}
}

func (x *Timeline) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Timeline) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Timeline) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Timeline) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Timeline) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

var File_api_ocp_timeline_api_ocp_timeline_api_proto protoreflect.FileDescriptor

var file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x63, 0x70, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x6f,
	0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a,
	0x1d, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x36, 0x0a, 0x1e, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64,
	0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x61, 0x64, 0x64, 0x65, 0x64,
	0x22, 0x51, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x74,
	0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x22, 0x34, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x6a, 0x0a, 0x17, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x26, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4f, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x08, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x22, 0x45, 0x0a, 0x15, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x68, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x29, 0x0a, 0x17, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x6b, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12,
	0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x32,
	0xbc, 0x06, 0x0a, 0x0e, 0x4f, 0x63, 0x70, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x41,
	0x70, 0x69, 0x12, 0x83, 0x01, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x12, 0x29, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69,
	0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x7c, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x12, 0x26, 0x2e, 0x6f, 0x63, 0x70, 0x2e,
	0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x14, 0x12, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x7a, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69,
	0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x12, 0x27, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74,
	0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x28, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x73, 0x12, 0x85, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x12, 0x29, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69,
	0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14, 0x2a, 0x12, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x83, 0x01, 0x0a, 0x10, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x12,
	0x29, 0x2e, 0x6f, 0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e,
	0x65, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x6f, 0x63, 0x70,
	0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x56, 0x31, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x1a, 0x0d,
	0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x3a, 0x01, 0x2a,
	0x12, 0x9b, 0x01, 0x0a, 0x16, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x56, 0x31, 0x12, 0x2f, 0x2e, 0x6f, 0x63,
	0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d,
	0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c, 0x69,
	0x6e, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x6f,
	0x63, 0x70, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x4d, 0x75, 0x6c, 0x74, 0x69, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6c,
	0x69, 0x6e, 0x65, 0x73, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1e,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22, 0x13, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x6c, 0x69, 0x6e, 0x65, 0x73, 0x2f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x3a, 0x01, 0x2a, 0x42, 0x4a,
	0x5a, 0x48, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f,
	0x6e, 0x63, 0x70, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x69, 0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6f, 0x63, 0x70, 0x2d, 0x74, 0x69, 0x6d,
	0x65, 0x6c, 0x69, 0x6e, 0x65, 0x2d, 0x61, 0x70, 0x69, 0x3b, 0x6f, 0x63, 0x70, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescOnce sync.Once
	file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescData = file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDesc
)

func file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescGZIP() []byte {
	file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescOnce.Do(func() {
		file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescData)
	})
	return file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDescData
}

var file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_ocp_timeline_api_ocp_timeline_api_proto_goTypes = []interface{}{
	(*MultiCreateTimelinesV1Request)(nil),  // 0: ocp.timeline.api.MultiCreateTimelinesV1Request
	(*MultiCreateTimelinesV1Response)(nil), // 1: ocp.timeline.api.MultiCreateTimelinesV1Response
	(*UpdateTimelineV1Request)(nil),        // 2: ocp.timeline.api.UpdateTimelineV1Request
	(*UpdateTimelineV1Response)(nil),       // 3: ocp.timeline.api.UpdateTimelineV1Response
	(*CreateTimelineV1Request)(nil),        // 4: ocp.timeline.api.CreateTimelineV1Request
	(*CreateTimelineV1Response)(nil),       // 5: ocp.timeline.api.CreateTimelineV1Response
	(*GetTimelineV1Request)(nil),           // 6: ocp.timeline.api.GetTimelineV1Request
	(*GetTimelineV1Response)(nil),          // 7: ocp.timeline.api.GetTimelineV1Response
	(*ListTimelineV1Request)(nil),          // 8: ocp.timeline.api.ListTimelineV1Request
	(*ListTimelineV1Response)(nil),         // 9: ocp.timeline.api.ListTimelineV1Response
	(*RemoveTimelineV1Request)(nil),        // 10: ocp.timeline.api.RemoveTimelineV1Request
	(*RemoveTimelineV1Response)(nil),       // 11: ocp.timeline.api.RemoveTimelineV1Response
	(*Timeline)(nil),                       // 12: ocp.timeline.api.Timeline
}
var file_api_ocp_timeline_api_ocp_timeline_api_proto_depIdxs = []int32{
	12, // 0: ocp.timeline.api.MultiCreateTimelinesV1Request.timelines:type_name -> ocp.timeline.api.Timeline
	12, // 1: ocp.timeline.api.UpdateTimelineV1Request.timeline:type_name -> ocp.timeline.api.Timeline
	12, // 2: ocp.timeline.api.GetTimelineV1Response.timeline:type_name -> ocp.timeline.api.Timeline
	12, // 3: ocp.timeline.api.ListTimelineV1Response.timelines:type_name -> ocp.timeline.api.Timeline
	4,  // 4: ocp.timeline.api.OcpTimelineApi.CreateTimelineV1:input_type -> ocp.timeline.api.CreateTimelineV1Request
	6,  // 5: ocp.timeline.api.OcpTimelineApi.GetTimelineV1:input_type -> ocp.timeline.api.GetTimelineV1Request
	8,  // 6: ocp.timeline.api.OcpTimelineApi.ListTimelineV1:input_type -> ocp.timeline.api.ListTimelineV1Request
	10, // 7: ocp.timeline.api.OcpTimelineApi.RemoveTimelineV1:input_type -> ocp.timeline.api.RemoveTimelineV1Request
	2,  // 8: ocp.timeline.api.OcpTimelineApi.UpdateTimelineV1:input_type -> ocp.timeline.api.UpdateTimelineV1Request
	0,  // 9: ocp.timeline.api.OcpTimelineApi.MultiCreateTimelinesV1:input_type -> ocp.timeline.api.MultiCreateTimelinesV1Request
	5,  // 10: ocp.timeline.api.OcpTimelineApi.CreateTimelineV1:output_type -> ocp.timeline.api.CreateTimelineV1Response
	7,  // 11: ocp.timeline.api.OcpTimelineApi.GetTimelineV1:output_type -> ocp.timeline.api.GetTimelineV1Response
	9,  // 12: ocp.timeline.api.OcpTimelineApi.ListTimelineV1:output_type -> ocp.timeline.api.ListTimelineV1Response
	11, // 13: ocp.timeline.api.OcpTimelineApi.RemoveTimelineV1:output_type -> ocp.timeline.api.RemoveTimelineV1Response
	3,  // 14: ocp.timeline.api.OcpTimelineApi.UpdateTimelineV1:output_type -> ocp.timeline.api.UpdateTimelineV1Response
	1,  // 15: ocp.timeline.api.OcpTimelineApi.MultiCreateTimelinesV1:output_type -> ocp.timeline.api.MultiCreateTimelinesV1Response
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_ocp_timeline_api_ocp_timeline_api_proto_init() }
func file_api_ocp_timeline_api_ocp_timeline_api_proto_init() {
	if File_api_ocp_timeline_api_ocp_timeline_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCreateTimelinesV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiCreateTimelinesV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTimelineV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTimelineV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimelineV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTimelineV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimelineV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTimelineV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTimelineV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTimelineV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTimelineV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTimelineV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Timeline); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ocp_timeline_api_ocp_timeline_api_proto_goTypes,
		DependencyIndexes: file_api_ocp_timeline_api_ocp_timeline_api_proto_depIdxs,
		MessageInfos:      file_api_ocp_timeline_api_ocp_timeline_api_proto_msgTypes,
	}.Build()
	File_api_ocp_timeline_api_ocp_timeline_api_proto = out.File
	file_api_ocp_timeline_api_ocp_timeline_api_proto_rawDesc = nil
	file_api_ocp_timeline_api_ocp_timeline_api_proto_goTypes = nil
	file_api_ocp_timeline_api_ocp_timeline_api_proto_depIdxs = nil
}
